### ISSUE TITLE
Extension size

### ISSUE THREAD

**Issue by FokkoVeegens** [jeffpriz/vsts-release-web-test#7]
I see the extension is almost 8.5Mb. It seems very big for what it does. Do you really need all node_modules to make it work? I'm not a node guru though...

**Comment by jeffpriz** [comment]
Yeah, this does seem to have grown a bit.. I had changed out the http npm object I was using a while back. I will take a peek to seem if I can do some cleanup on the npm packages that are being pulled in.  Previous version was closer to 6Mb so I will look in to what's going on here. thanks,

**Comment by jeffpriz** [comment]
so a little poking around, I'm going to blame the recent size increase on the newest task-library package "azure-pipelines-task-lib" as that was the last change I really made that may have added some size to the package (that update was needed because Microsoft updated the objects from "vsts" to "azure devops" branding, and is required for packages ).  The rest of the packages are what get used.. the tslib package is needed to create the task and be able to output data to azure devops, the request and request-promise-native are the http request object that I am using.. so I suppose I could try to find a smaller http request object if that were needed, but I had just swapped to this one as it was the better performing/more reliable/more functional object vs. the one I had used previous to this.    

I double checked to make sure I wasn't including some crazy sized images in the vsix.. but the icons and images for the readme are fairly small.. 

If you would like to see if you can re-work it and get rid of something I'll check out an PR sent over.

thanks

jeff
